name: Automatic Infra-scripts Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    uses: AventusDAO/shared-workflows/.github/workflows/automatic-releases.yaml@v5.9.0
    with:
      default_bump: minor
    secrets:
      envPat: ${{ secrets.GITHUB_TOKEN }}
