name: Automatic Infra-scripts Release

on:
  push:
    branches:
      - master

jobs:
  github-release:
    uses: Aventus-Network-Services/Infra-scripts/.github/workflows/automatic-releases.yaml@v5.2.0
    with:
      default_bump: minor
    secrets:
      envPat: ${{ secrets.GITHUB_TOKEN }}